package com.chitter.chitter.Model;

import javax.persistence.*;

//@Entity: Declares the domain class as an entity - basically an object we want to store in the database
@Entity
public class Peep {

//  @Id: The id attribute has been annotated with @Id to specify this attribute as the primary key in the database
//  @GeneratedValue(strategy = GenerationType.AUTO): Whenever we create a new object in the database the id should be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String content;

    public Peep() {

    }

    public Peep(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
